swagger: "2.0"
info:
  title: "Hello world API"
  version: "1.0.1"
  contact: 
    email: "oscar.garcia@mariachi.io"
    name: "OGA"
    url: "htts://spring.io"
  description: "Api for greeting new springboot devs"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.orglicenses/apache2.0.html"
  termsOfService: "http://swagger.io"
basePath: "/api"
tags:
  - name: "Hello group"
    description: "Everthing about hello world"
    externalDocs:
      url: "http://spring.io"
      description: "Find out more about the businesssssss"
schemes:
  - http
  - https
paths:
  /greeting:
    get:
      tags:
        - "Hello group"
      description: "Get all the greetings on the world"
      operationId: "getAllGreetings"
      produces:
        - "application/json"
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Greeting"
        404:
          description: Greetings not found
    post:
      parameters:
        - name: greeting
          in: body
          schema:
            $ref: "#/definitions/Greeting"
          required: true
      operationId: addGreeting
      summary: "Api for adding greetings"
      produces:
      - "application/json"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Greeting"
  /greeting/{message}:
    get:
      tags:
        - "Hello group"
      description: "Get one greeting"
      operationId: "getGreeting"
      produces:
        - "application/json"
      parameters:
        - name: "message"
          in: path
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Greeting"
        404:
          description: Greeting not found
definitions:
  Greeting:
    required:
      - "message"
      - "id"
    properties: 
      id:
        type: integer
        format: "int64"
        example: "1234"
        description: "Greeting internal identifier"
      message:
        type: string
        example: "Hello world!!!!!!"
        description: "Greeting to send to the world"
      location:
        type: string
        example: "CDMX"
        description: "Source location of the greeting"